spring.application.name=TaskManager

# Server Properties
server.port=9090

# MongoDb Properties
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=TaskManager

# Logging Properties
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG